### ISSUE TITLE
Matrix File

### ISSUE THREAD

**Issue by Christina-Straham** [VanAndelInstitute/ExpDesign2021#2]
I'm getting an error when I try to run this chunk.
```r
library(Matrix)
umi_counts <- as(readMM("matrix.mtx.gz"), "dgCMatrix")
```
I can't find where in the markdown to download the Matrix file.

**Comment by ttriche** [comment]
See updated project 2 Markdown for a URL-based solution to directly recreate the downsampled matrix.
